UI/UX: error messages, hover states, light cleanup
error: uses the error thrown by the domains resolver
hover: clipboards and verification time are shown by default instead of being hidden by hover
cleanup: clearer dnsRecord subcomponent